;;; majapahit-themes-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from majapahit-dark-theme.el

(register-definition-prefixes "majapahit-dark-theme" '("majapahit-dark"))


;;; Generated autoloads from majapahit-light-theme.el

(register-definition-prefixes "majapahit-light-theme" '("majapahit-light"))


;;; Generated autoloads from majapahit-themes.el

(when load-file-name (add-to-list 'custom-theme-load-path (file-name-as-directory (file-name-directory load-file-name))))
(register-definition-prefixes "majapahit-themes" '("create-majapahit-theme" "majapahit-theme-"))

;;; End of scraped data

(provide 'majapahit-themes-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; majapahit-themes-autoloads.el ends here
