;;; vim-powerline-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from vim-colors.el

(register-definition-prefixes "vim-colors" '("powerline--"))


;;; Generated autoloads from vim-powerline-theme.el

(register-definition-prefixes "vim-powerline-theme" '("check-in-list" "pl/" "powerline-vimish-theme"))

;;; End of scraped data

(provide 'vim-powerline-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; vim-powerline-autoloads.el ends here
