;;; gendoxy-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from gendoxy.el

(autoload 'gendoxy-header "gendoxy" "\
Generate generic template header for current file" t)
(autoload 'gendoxy-group-start "gendoxy" "\
Generate general template for the beginning of a block of items" t)
(autoload 'gendoxy-group-end "gendoxy" "\
Generate general template for the beginning of a block of items" t)
(autoload 'gendoxy-group "gendoxy" "\
Generate general template for a block of items and its items if requested" t)
(autoload 'gendoxy-group-header "gendoxy" "\
Generate general template for a block of items" t)
(autoload 'gendoxy-tag "gendoxy" "\
Generate general template for source item in current line and its items" t)
(autoload 'gendoxy-tag-header "gendoxy" "\
Generate general template for source item in current line" t)
(register-definition-prefixes "gendoxy" '("gendoxy-"))

;;; End of scraped data

(provide 'gendoxy-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; gendoxy-autoloads.el ends here
