;;; cpp-auto-include-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from cpp-auto-include.el

(autoload 'cpp-auto-include "cpp-auto-include" "\
Insert needed C++ headers and remove unneeded headers." t)
(register-definition-prefixes "cpp-auto-include" '("cpp-auto-include--"))

;;; End of scraped data

(provide 'cpp-auto-include-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; cpp-auto-include-autoloads.el ends here
