;;; pippel-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from pippel.el

(autoload 'pippel-install-package "pippel" "\
Prompt user for a string containing packages to be installed.

(fn ARG)" t)
(autoload 'pippel-list-packages "pippel" "\
Display a list of installed packages." t)
(autoload 'pippel-list-user-packages "pippel" "\
Display a list of user-installed system packages." t)
(register-definition-prefixes "pippel" '("pippel-"))

;;; End of scraped data

(provide 'pippel-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pippel-autoloads.el ends here
