;;; omnisharp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from omnisharp.el

(autoload 'omnisharp-mode "omnisharp" "\
Omnicompletion (intellisense) and more for C# using an OmniSharp

server backend.

This is a minor mode.  If called interactively, toggle the
`omnisharp mode' mode.  If the prefix argument is positive,
enable the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable
the mode if ARG is nil, omitted, or is a positive number.
Disable the mode if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `omnisharp-mode'.

The mode's hook is called both when the mode is enabled and when
it is disabled.

(fn &optional ARG)" t)
(autoload 'omnisharp-start-omnisharp-server "omnisharp" "\
Starts an OmniSharp server for a given path to a project or solution file

(fn &optional NO-AUTODETECT)" t)
(autoload 'omnisharp-stop-server "omnisharp" "\
Stops Omnisharp server if running." t)
(autoload 'omnisharp-reload-solution "omnisharp" "\
Restarts omnisharp server on solution last loaded" t)
(autoload 'omnisharp-check-alive-status "omnisharp" "\
Shows a message to the user describing whether the
OmniSharpServer process specified in the current configuration is
alive.
\"Alive\" means it is running and not stuck. It also means the connection
to the server is functional - I.e. The user has the correct host and
port specified." t)
(autoload 'omnisharp-check-ready-status "omnisharp" "\
Shows a message to the user describing whether the
OmniSharpServer process specified in the current configuration has
finished loading the solution." t)
(autoload 'omnisharp-install-server "omnisharp" "\
Installs OmniSharp server locally into ~/.emacs/cache/omnisharp/server/$(version)

(fn REINSTALL)" t)
(autoload 'company-omnisharp "omnisharp" "\


(fn COMMAND &optional ARG &rest IGNORED)" t)
(register-definition-prefixes "omnisharp" '("omnisharp-"))


;;; Generated autoloads from omnisharp-auto-complete-actions.el

(register-definition-prefixes "omnisharp-auto-complete-actions" '("ac-" "omnisharp-"))


;;; Generated autoloads from omnisharp-code-structure.el

(register-definition-prefixes "omnisharp-code-structure" '("omnisharp--cs-"))


;;; Generated autoloads from omnisharp-current-symbol-actions.el

(register-definition-prefixes "omnisharp-current-symbol-actions" '("omnisharp-"))


;;; Generated autoloads from omnisharp-format-actions.el

(register-definition-prefixes "omnisharp-format-actions" '("omnisharp-"))


;;; Generated autoloads from omnisharp-http-utils.el

(register-definition-prefixes "omnisharp-http-utils" '("omnisharp-"))


;;; Generated autoloads from omnisharp-navigation-actions.el

(register-definition-prefixes "omnisharp-navigation-actions" '("omnisharp-"))


;;; Generated autoloads from omnisharp-server-actions.el

(register-definition-prefixes "omnisharp-server-actions" '("omnisharp--"))


;;; Generated autoloads from omnisharp-server-installation.el

(register-definition-prefixes "omnisharp-server-installation" '("omnisharp--"))


;;; Generated autoloads from omnisharp-server-management.el

(register-definition-prefixes "omnisharp-server-management" '("comment" "make-omnisharp--server-info" "omnisharp-"))


;;; Generated autoloads from omnisharp-settings.el

(register-definition-prefixes "omnisharp-settings" '("omnisharp-"))


;;; Generated autoloads from omnisharp-solution-actions.el

(register-definition-prefixes "omnisharp-solution-actions" '("omnisharp-"))


;;; Generated autoloads from omnisharp-unit-test-actions.el

(register-definition-prefixes "omnisharp-unit-test-actions" '("omnisharp-"))


;;; Generated autoloads from omnisharp-utils.el

(register-definition-prefixes "omnisharp-utils" '("omnisharp-"))

;;; End of scraped data

(provide 'omnisharp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; omnisharp-autoloads.el ends here
